equinor/oneseismic-api

api/query.go
cmd/query/main.go
internal/vds/vds.go
internal/vds/vds_test.go
tests/e2e/test_slice.py

The main work of this PR makes changes to how the slice endpoints accepts parameters. Additionally it does a bit of refactoring and misc work to facilitate these changes, as well as making the code more testable. Tests are left for the next PR
Endpoint /slice and /slice/metadata now expects the following payload:
```
{
"direction": "inline",
"lineno": 9961,
"vds": "container/subpath",
"sas": "sv=..."
}
```
Both endpoints still support GET and POST methods. The GET methods
expects the payload to be URLescaped and passed as query parameter
'query'. I.e. ?query=urlescape(payload.json). The POST methods expect
the json to be passed in the request body.
Examples
--------
Get:
```
curl -G --data-urlencode query@body.json "http://localhost:8080/slice/metadata"
```
Post:
```
curl -H …
```

Make sas-token a part of payload in /slice & /slice/metadata

---

.github/workflows/unit.yaml

As we still build openvds from scratch, it takes a long time and might
not be very efficient to run on every PR.

Add go unit tests to github actions

---

cmd/query/main.go
go.mod

This commits add support for clients to ask for their response to be
gzip'd by specifying 'gzip' as part of the 'Accept-Encoding' header.
At the moment we priorities compression performance over compression
ratio. Compressing to aggressivly will have a negative impact on
cloud-to-cloud. This might change if we do more benchmarking.
The current compression ratio is about 2 for a farily dense binary
fence.

Add gzip support to endpoints

---

radixconfig.yaml

Two environments in this stage are useful when we want to test a special server configuration without disrupting our main environment. Environment can always be stopped whenever it is not needed.
Though I do accept "we do not need it" in case we would forget to manually stop that after each new deploy and whenever it is not used.

Add secondary environment to radix

---

.github/workflows/analyzer.yaml
Dockerfile

closes #64 
Repeating args becomes annoying, but I think I failed to find a better solution.
There was something about declaring them at the very top of the docker file, but that seemed too far away from the context.
Not sure if we can do that any faster. The other PR introduces option to run E2E tests using a built image stored in azure, but as far as I recall that approach can't be used for unit tests mostly because secrets are unavailable in github PRs and publicly org-hosting someone else's image is strange.
Feel free to do with this PR whatever you want to :smile:  Submitting it now in case fixes would fit nice into your planned refactoring.

Golang static checker

---

Dockerfile

The Go container used by the Dockerfile has been updated to use a new release of Alpine Linux (3.17). This breaks the installation procedure of OpenVDS within the container as OpenSSL v3 instead of v1 is used within the new release. Thus we pin the Alpine version to 3.16 which uses OpenSSL v1.

Pin Alpine Linux version of Docker container to Alpine Linux 3.16

---

Dockerfile

In pull request #72 the Alpine Linux version had been pinned to 3.16. This pull request pins the version also for the runner defined in the Dockerfile.

Pin Alpine version for Docker runner image

---

api/query_test.go
internal/vds/vds.cpp
internal/vds/vds_test.go

The axis information does not match the way the data is ordered. One can argue that it's the data that should be transposed, not the axis as that seams to be the most natural orientation for e.g. plotting. However, I'm unsure if we should transpose data server side as that imposed additional compute on us.
Hence this commit reorders the metadata rather than the data, to make sure they correspond. This descision might be revisited before we do a proper versioned release of the API.

Swap axis order in slice metadata

---

api/request.go

This struct hold information about the requested resource (vds) and it's embed in SliceRequest, FenceRequest and MetadataRequest. The new name reflects this fact better than the old. BaseRequest was a poor name as it incorrectly suggested some form of inheritance.

Rename BaseRequest -> RequestedResource

---

cmd/query/main.go
internal/logging/logging.go

This commit slightly changes the request log format to include timezone, and excludes query-parameters from the path. The later solves the sas-token logging described in #87. It does not log requests at all. This is for a later PR

Add custom gin logger

---

.github/actions/load_openvds_image/action.yaml
.github/workflows/analyzer.yaml
.github/workflows/e2e.yaml
.github/workflows/performance.yaml
.github/workflows/performance_user_input.yaml
.github/workflows/unit.yaml
Dockerfile
README.md
tests/e2e/test_requests.py

1. To see if main assumption of cache from master being accessible in PR holds, we need to merge first, but at least it holds for stuff pushed to other branches.
2. When openvds must be updated, cache with new version name shouldn't exist anywhere and all the jobs would have to build it on their own. So everything should be fine.
3. Need to push to Radix to make sure dockerfile still builds, but think it should be fine.

Openvds github action image cache

---

api/endpoint.go
api/request.go
internal/logging/logging.go

Log only successfully parsed requests. Goal of Requests logging is to assist in future debugging of server behavior (which we got burned on recently).
For malformed requests enough information is returned to the user. So it is their responsibility to fix the request. Us logging it won't help anything.
While information can be tied to the user's ip, it is not stored anywhere for further processing.
SAS are not logged. Any other relevant information (aka vds) while isn't public, shouldn't do any harm if known to anyone with access to the server logs.
closes #87

Log requests

---

api/endpoint.go
internal/vds/boundingbox.cpp
internal/vds/boundingbox.h
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go

Overall this PR does some basic cleanup which includes renaming and moving of code into different files. The PR changes the following things:
- Enumeration `axis` is renamed to `api_axis_name`. This frees up the name `Axis` such that it can be used in a follow-up PR. It is also closer to what this enumeration represents: The name of an axis in our API. 
- Moved the `BoundingBox` class into its own header and implementation file. The `vds.cpp` is quite large and follow-up PRs are supposed to introduce additional classes which should be in the own headers in implementations files as well.
- Removes a parameter from functions that obtain metadata for slices as the parameter was never used.
- Rename `vdsbuffer` to `response` as the name better reflects the content of the struct. 
This and …

Cleanup of C++ core (part 1 of refactoring)

---

cmd/query/main.go

As our server is not expected to be used by anyone and company proxies are usually sophisticated enough to bypass default proxy checks, trusting no proxy shouldn't affect us in any way and will make gin happy.
closes #106

Trust no proxies

---

api/endpoint.go
internal/vds/connection.go
internal/vds/datahandle.cpp
internal/vds/datahandle.hpp
internal/vds/errors.go
internal/vds/exceptions.hpp
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go

This PR implement a new design of the CGO / CAPI. There are several motivations for this new design:
1. Give more control to Go
By exposing open openvds handles to Go, they can be kept alive between function calls which will allow us to drive more of the workflow directly from GO. 
2. Performance
Avoiding the need to re-open the same vds handle multiple times also has a positive outcome on performance
3. Better errorhandling
The new error codes means that we can map C++ exceptions to C error-codes, which are them mapped to Go Errors and finally to appropriate HTTP status codes which are passed to the callers. This will enable us to return more accurate status codes.
The new design also opens other doors, that are not part of this PR:
The most noteworthy is to allocate data buffers that …

Redesign the CGO / C-API and propagate C++ exceptions to Go

---

api/request_test.go
cmd/query/formats_test.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
internal/cache/cache_test.go
internal/vds/vds_test.go

When we introduced the module to the repository for the first time, we didn't go back and update old tests. Hence we have a good mix of manually comparisons and the use of require. 
To keep life simple for us, I've also removed all uses of the module assert.

Consistently use Go module "require" for testing

---

api/endpoint.go
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go
tests/e2e/test_requests.py

Geospacial information is often integral in order to relate seismic to other data sources. Currently we provide the bounding box of the entire cube through /metadata. However, when fetching a (vertical) slice the user would have to manually do coordinate mapping to get the geospacial position of the slice. This commit adds this information to the slice metadata. For horizontal slices, this is just the bounding box, while for vertical slices this is essentially a linestring.
There are many ways to implement this, and I landed on basing it on the SubVolume bounds. This has 2 benefits. Firstly, it ensures consistency between fetch_slice and fetch_slice_metadata, and secondly, it is future proof if we ever deside to implement sub-slicing.

Return geospacial information in slice metadata

---

radixconfig.yaml

It is troublesome to find a good place to keep allowed storage accounts list. Thus we want to change to a better solution than keeping it locally in team notes.
Keeping the list as env variable in Radix (not as secret) would make it visible and more easily changable, but Radix is not a permanent storage. So if our app gets deleted, the list goes with it.
Other suggestions like finding out if storage account belongs to specified tenant seem not be an option for us as they require far wider privileges than the ones we have.
Keeping allowlist as a secret in Key Vault assures list is persistent. We still have to update the list ourselves (unless we create a separate solution on top), but the team can see previous versions of the secret and thus create a new version of the same secret with …

Use Azure Key Vaults to obtain allowlist in Radix

---

internal/core/core.go

When we are creating a Regular Surface, we create a 1D array of data points and assign this to 'cdata' variable. This variable is then further passed to the C Regular Surface function as a pointer. However, as 'cdata' is declared within the function, it goes out of scope as soon as the function returns, and Golang memory management reuses that space for other variables, which can result in memory conflicts and errors.
To resolve this issue, in this change, we are modifying the structure of the Regular Surface and making 'cdata' a member of the struct so that it holds the memory as long as the struct remains valid.
This solution ensures that 'cdata' has a fixed location and will not be affected by other declarations.
closes #174

Make cdata array member of regular surface struct

---

internal/core/capi.cpp
internal/core/capi.h
internal/core/cppapi.hpp
internal/core/cppapi_data.cpp
internal/core/regularsurface.cpp
internal/core/regularsurface.hpp
tests/gtest/CMakeLists.txt
tests/gtest/cppapi_test.cpp
tests/gtest/regularsurface_test.cpp

First part of the attributes between surfaces saga!
Totally ignored suggested threshold value. Let me know if there was actual user need for it for some reason and what is the the usecase. Without it I am just snapping to closest point on the secondary surface grid and taking whichever value is there.

Attributes between surfaces: Align surfaces

---

api/endpoint.go
api/request.go
cmd/query/formats_test.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
docs/attribute.md
internal/core/core.go
internal/core/core_test.go
internal/core/cppapi_data.cpp
tests/e2e/test_requests.py
tests/performance/helpers/horizon-helpers.js

RegularSurface is displayed in the docs as `core.RegularSurface`, but I don't see how to fix that.

Regularsurface as parameter

---

api/endpoint.go
api/request.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
internal/core/capi.cpp
internal/core/capi.h
internal/core/core.go
internal/core/core_test.go
internal/core/cppapi.hpp
internal/core/cppapi_data.cpp

The current behaviour is to throw an error if any coordinate provided in the request falls outside the boundaries of the seismic volume. However, with this pull request, the user will now be able to submit requests containing such coordinates and the response will return fillvalues for all values lying outside the seismic cube.
closes #116

Allow out-of-bound fence requests

---

cmd/query/main_test.go
cmd/query/utils_main_test.go
internal/core/attribute.hpp
internal/core/axis.cpp
internal/core/axis.hpp
internal/core/capi.cpp
internal/core/core.go
internal/core/core_test.go
internal/core/cppapi_data.cpp
internal/core/cppapi_metadata.cpp
internal/core/interpolation.hpp
internal/core/subvolume.cpp
tests/e2e/test_requests.py
tests/performance/script-constant-horizon.js
tests/performance/script-random-horizon.js

closes #191
Expose stepsize (stride) in the metadata endpoint. The purpose here is to pre-calculate the value for the user. 
All references to stride has been changed to stepsize for consistency.

Expose stepsize in the metadata endpoint

---

internal/core/attribute.cpp
internal/core/cppapi_data.cpp
internal/core/regularsurface.cpp
internal/core/regularsurface.hpp
tests/gtest/cppapi_test.cpp
tests/gtest/regularsurface_test.cpp

Introducing parameters via subscript to RegularSurfaces. 
Two types of subscript indexing is available. 
Single subscript has only one integer parameter and is used as follows:
```
std::size_t value = surface[row_nr * nr_of_colums + col_nr];
surface[row_nr * nr_of_colums + col_nr] = value;
```
Second subscript is defined for the Point struct and, thus indirectly allows two parameters:
```
Point p;
p.x = row;
p.y = col;
std::size_t value = surface[p];
surface[p] *= 2;
```
Tests checking read and write as well as comparison to the value function is available in "regularsurfacesubscript_test.cpp".
Close #195

Introduce regular surface subscript

---

internal/core/CMakeLists.txt
internal/core/capi.cpp
internal/core/cppapi_data.cpp
internal/core/cppapi_metadata.cpp
internal/core/datahandle.cpp
internal/core/datahandle.hpp
internal/core/regularsurface.cpp
internal/core/regularsurface.hpp
internal/core/subcube.cpp
internal/core/subcube.hpp
tests/gtest/cppapi_test.cpp

Two preparations for the next PR which will try to restructure the way we manage attributes (successfully or not is a different question)
1. Subvolume -> Subcube as I will likely name another structure Subvolume.
2. BoundedPlane was needed for nicer handling of plane information as this Subvolume kinda will represent data between RegularSurfaces based on the same horizontal stuff.
Changes should however make sense even if next PR is never merged.

Subcube + BoundedPlane

---

api/endpoint.go
api/request.go
api/request_test.go

I've been irritated for a while that our endpoints are copied whenever we need a new one.
This attempts to extract away currently duplicated logic.

Endpoint duplication

---

docs/attribute_along.md
docs/attribute_between.md
internal/core/attribute.cpp
internal/core/attribute.hpp
internal/core/core.go
internal/core/core_attributes_test.go
internal/core/cppapi_data.cpp
internal/core/ctypes.h

Added a new attribute 'min_at' that will return the position of the minimum value in sample axes for both along the surface and between the surfaces.
Note:
This is not the final PR, but the implementation for only the minimum value position. If we agree with these changes, then I will add the rest of the attributes, which are similar to this.
closes #198

Add position of minimum value attribute

---

internal/core/cppapi_data.cpp
internal/core/subcube.cpp
internal/core/utils.hpp

When we are constructing error strings in C++, we often include coordinates or other floating point values. By default, these numbers include 6 digits, which can be unnecessary in many cases.
Therefore, setting the floating point precision to 2 decimal digits to eliminate any unnecessary noise.
closes #193

Adjust float values precision in C++ error strings

---

tests/e2e/test_requests.py

In our e2e test case, we  download the latest version of the blob library every time we run new container. However, the recent release of azure-storage-blob 12.19.0 has made it mandatory to include the permission argument in order to generate a SAS token.
Therefore, passing an empty parameter that would lead to an exception from the blob library and break code. So that testcase is no longer relevant and its good to remove.
[ref](https://github.com/Azure/azure-sdk-for-python/commit/86759fffbae2c93771607aacd2e6e5697b5b0bda)

Remove unnecessary e2e testcase

---

api/endpoint.go
api/request.go
api/request_test.go
cmd/query/formats_test.go
cmd/query/main.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
internal/core/capi.cpp
internal/core/capi.h
internal/core/core.go
internal/core/core_attributes_test.go
internal/core/core_fence_test.go
internal/core/core_general_test.go
internal/core/ctypes.h
tests/e2e/shared_test_functions.py
tests/e2e/test_error_propagation.py
tests/e2e/test_happy_requests.py
tests/e2e/test_security.py

Introduce difference between two cubes as an option for fence, slice and attribute end points. 
There are no breaking changes with requests to previous version of the API. By proving the a list of VDS URLs, SAS tokens and a binary operator the user can make the request on the resulting data set. For instance a fence request to the subtraction of one cube from another only calculate the difference on traces in the fence request.

Difference endpoint

---

internal/core/CMakeLists.txt

Building the tests were failing on systems where Boost is not in the default search path for include directories, e.g., if Boost was installed with Homebrew.
The change also makes the dependency on liboost more explicit as CMake will print an error message if CMake does not find Boost during the configuration stage.
```
$ cd build/ && make
[...]
[ 50%] Building CXX object internal/core/CMakeFiles/cppcore.dir/subcube.cpp.o
[ 50%] Built target gtest
[ 53%] Building CXX object internal/core/CMakeFiles/cppcore.dir/subvolume.cpp.o
/Users/AEJ/projects/github/vds-slice/internal/core/metadatahandle.cpp:6:10: fatal error: 'boost/algorithm/string/join.hpp' file not found
#include <boost/algorithm/string/join.hpp>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** …
```

Make CMake search for Boost libraries in C++ tests

---

radixconfig.yaml
radixconfig_playground.yaml

Some production app is partly created from test branches containing this PR code, but it will be set up properly during/after this PR merge.
Note: We can't have 0 replicas. If we set it like so, it is impossible to start the component. So it seems like we need to push to test environments only when we need to and stop them explicitly once we don't need them.
Alternative is to talk to Radix team and ask them to implement containers in stopped state.

Prepare radixconfig for production

---

.github/workflows/performance.yaml
.github/workflows/performance_user_input.yaml
tests/performance/Dockerfile
tests/performance/execute.sh
tests/performance/helpers/metrics-helper.js
tests/performance/helpers/report-helpers.js
tests/performance/helpers/request-helpers.js
tests/performance/performance.py
tests/performance/prometheus-template.yml
tests/performance/script-constant-fence.js
tests/performance/script-constant-timeslice.js
tests/performance/script-random-fence.js
tests/performance/script-random-inlineslice.js
tests/performance/script-sequential-inlineslice.js

Sends data to the Azure Monitor service via local prometheus.
What tests we want to run, what configurations we need, what we want to show in grafana is a different topic, but if you have any immediate improvement suggestions - comment straight away.
`Performance tests` workflow would be configured the way so every run over provided ENDPOINT secret sends data to the azure monitor instance. We'd need to decide whether we want to run that on schedule on not, also against which endpoint.
Currently runs can be found on my fork and tests results should be visible in grafana.
`Performance (manual)` workflow doesn't send anything anywhere.
Resources (Azure Monitor and Grafana) can be found in our Azure test resource group with prefix performance.

Visualize performance tests results

---

api/endpoint.go
internal/metrics/metrics.go
internal/metrics/metrics_test.go

Playground grafana is updated with respective panel, production grafana will be changed after merge (might need to discuss the need to exclude test storage account from all the metrics)

Expose storage account in metric

---

tests/gtest/CMakeLists.txt
tests/gtest/datahandle_attribute_test.cpp
tests/gtest/datahandle_fence_test.cpp
tests/gtest/datahandle_slice_test.cpp
tests/gtest/test_utils.cpp
tests/gtest/test_utils.hpp

Changes the way slice/fence/attributes gtests perform verifications and make all 3 to use the same class.
(metadata tests also can be unified with them, in theory, but it is separate enough issue I didn't feel the compelling need to do)

Index to annotation in cube intersection gtests

---

radixconfig.yaml
radixconfig_playground.yaml

Validation schemas seem to work for various editors and extensions.

Use validation schemas in radixconfig files

---

api/middleware/request_blocker.go
cmd/query/main.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
radixconfig.yaml
radixconfig_playground.yaml

We would like to prevent some requests, like slack back-linking, from spoiling our statistics.
It might not really be a solution, but lets see what it leads to.

Allow blocking requests based on ip/user-agent

---

Dockerfile
tests/performance/script-random-inlineslice-wait.js

Looks like the reason for slowness I've been investigating is openssl version.
Test results on slice retrieval for 500_300_2000 file with 2.5 minutes wait time between requests (which is closer to standard user pattern than hammering requests) :
Before:
`   ✓ request_time_Manual_execution...: avg=1.79s     min=1.67s    med=1.77s    max=1.92s    p(95)=1.92s    p(99)=1.92s    count=8`
After:
`   ✓ request_time_Manual_execution...: avg=1.07s    min=912.93ms med=1.06s    max=1.41s    p(95)=1.31s    p(99)=1.39s    count=8`

Use new openssl in open-vds

---

Dockerfile
radixconfig.yaml
tests/performance/helpers/metrics-helper.js

Master failing on memory tests: tried to investigate why debug build fails myself, also failed, so submitted [issue](https://community.opengroup.org/osdu/platform/domain-data-mgmt-services/seismic/open-vds/-/issues/251) to openvds. They don't have resources to work on it, so reverting.

Openvds azure manager thread count

---

.github/workflows/snyk.yaml
Dockerfile

What we discussed - we do not monitor openvds and we probably should, to not miss some critical issue.
I am not sure if these would somehow be repeated by snyk every couple of days (or similar), or if we would want to run the workflow on schedule.
```
schedule:
- cron: "05 05 * * MON"
```
We could see how it goes after some time.

Monitor openvds with snyk

---

Dockerfile
radixconfig.yaml
radixconfig_playground.yaml

I will run additional comprehensive tests on test-large once it is merged.
Tests on playground (with less powerful machines) showed that performance difference is inside error margin.
I am kinda worried that ARM actually might have worse performance in our case, but can't find anything conclusive in the web.
Also an option is to switch only test-large environment to arm, but I am not fond of having production and test-large one to be different.
Github doesn't provide standard arm machines yet, so we can't switch tests to them.

Use ARM in Radix setups

---

tests/e2e/Dockerfile
tests/utils/cloud.py

Fix DeprecationWarning.
DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
expiry = datetime.datetime.utcnow() + datetime.timedelta(seconds=lifespan)

Use timezone aware object for UTC

---

Dockerfile
tests/memory/Dockerfile
tests/performance/Dockerfile

Building the docker image give the following warning:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match

Fix casing do not match warnings

---

tests/performance/Dockerfile

Performance tests must also use python 3.12 due to 764bd59bc8f69fe34c11bc7a976197b4c2707b81

Use python 3.12 in performance tests
