equinor/oneseismic-api

Dockerfile

Not run on Radix yet, but hopefully will run and not report so many issues as final size is way smaller.

Simplify docker image

---

api/query.go
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go

We know that that vds interpolation has some known bugs, but we still
expose it as is.

Expose vds interpolation in api

---

api/query.go
api/query_test.go
docs/fence.md
tests/e2e/test_requests.py

Fence request names

---

.github/workflows/e2e.yaml
.github/workflows/performance.yaml
.github/workflows/performance_user_input.yaml
testdata/varsize/convert_varsize.sh
testdata/varsize/make_varsize.py
tests/performance/Dockerfile
tests/performance/helpers/fence-helpers.js
tests/performance/helpers/metadata-helpers.js
tests/performance/helpers/report-helpers.js
tests/performance/helpers/request-helpers.js
tests/performance/helpers/slice-helpers.js
tests/performance/performance.py
tests/performance/requirements-dev.txt
tests/performance/script-constant-fence.js
tests/performance/script-constant-timeslice.js
tests/performance/script-random-fence.js
tests/performance/script-random-inlineslice.js
tests/performance/script-sequential-inlineslice.js
tests/performance/script-various-requests.js

Not exactly sure what scenarios/thresholds we should use, but lets see and find out if anything would be useful at all.

Add performance tests

---

api/query_test.go
go.mod
tests/e2e/test_requests.py

Again not sure if that is useful in any way, but probably won't hurt.

Metadata tests

---

api/query_test.go
internal/vds/vds.go
internal/vds/vds_test.go

This PR addressed issues reported from the newly introduced golang static checker CI workflow (#64). It's purpose is to make this CI job green.

Static checker fixups

---

api/endpoint.go
api/endpoint_test.go
internal/vds/connection.go
internal/vds/vds.go
internal/vds/vds_test.go

This PR does 2 things.
The main purpose of this PR is to fix #80. But to get there it first refactors how we handle vds connections in go to a more general approach. This refactoring makes the implementation of the fix more elegant. The design of the new connection is also coloured by some planned expansions needed when implementing caching, which are not part of this PR.

Sas srt validation and connection-refactoring

---

.github/workflows/e2e.yaml
.github/workflows/performance.yaml
.github/workflows/performance_user_input.yaml
tests/e2e/Dockerfile
tests/e2e/requirements-dev.txt
tests/e2e/test_requests.py
tests/performance/Dockerfile
tests/performance/helpers/metrics-helper.js
tests/performance/helpers/report-helpers.js
tests/performance/helpers/request-helpers.js
tests/utils/cloud.py

Grew up a bit beyond caching as I discovered new small things to do when trying to figure out what I am doing wrong.
It would be nice to one day discuss and agree on the following things for when we move to production server. For now I chose what I chose, but it is up for discussion.
1. Do we assume our storage accounts are simple storage account, Data Lake Gen 2 or both. Do we set in stone which one we use in e2e tests, or would it be configurable.
2. What would be our test structure to get the best from performance tests
- we now finally got slices with remotely solid time where Erlend said "no, that's not fast enough". Which means there might be something to include into the suite. Currently all the numbers are "this are the numbers we got, because we don't really know what we want"
- …

Cache tests

---

internal/vds/datahandle.cpp
internal/vds/datahandle.hpp
internal/vds/vds.cpp

This PR includes several small improvements like removal of unused includes, cleanup, and the reduction of code duplication.

Post refactor improvements

---

internal/vds/datahandle.cpp
internal/vds/datahandle.hpp
internal/vds/vds.cpp

Revert "Post refactor improvements"

---

cmd/query/main_test.go
internal/vds/metadatahandle.cpp
internal/vds/metadatahandle.hpp
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds_test.go
tests/e2e/test_requests.py

Issue: https://github.com/equinor/vds-slice/issues/122

Added display name in metadata response

---

docs/attribute.md
internal/vds/attribute.cpp
internal/vds/attribute.hpp
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go

closes https://github.com/equinor/vds-slice/issues/127

add standard deviation attribute

---

README.md
tests/e2e/test_requests.py

E2e readme

---

api/endpoint.go
api/request.go
api/request_test.go
cmd/query/main_test.go
tests/e2e/test_requests.py

Allow SAS token authentication from vds urls

---

docs/attribute.md
internal/vds/attribute.cpp
internal/vds/attribute.hpp
internal/vds/vds.cpp
internal/vds/vds.go
internal/vds/vds.h
internal/vds/vds_test.go

Attribute median

---

api/request.go
api/request_test.go
internal/core/connection.go

Add explicit port number support in vds URL

---

cmd/query/main_test.go
internal/core/core.go
internal/core/core_test.go
internal/core/cppapi_metadata.cpp
internal/core/metadatahandle.cpp
internal/core/metadatahandle.hpp
tests/e2e/test_requests.py

Add time import stamp field in metadata response

---

cmd/query/main.go
internal/cache/cache.go
internal/cache/cache_test.go

Cache entry size

---

CMakeLists.txt
Dockerfile
README.md
internal/core/CMakeLists.txt
tests/gtest/CMakeLists.txt
tests/gtest/cppapi_test.cpp

Majority of our logic lives in C++ and it seems like it becomes difficult to test everything through go interface. Hence introducing test suite for C++.
Gtest was chosen out of curiosity. It seems like there shouldn't be much difference between the frameworks as all work reasonably well and have their frustrations.
Remarks:
1. I don't know what I am doing in cmake!
2. You sure you still don't think we want a picture with 10 samples / unaligned surface in source code?

Introduce gtest

---

api/endpoint.go
api/request.go
cmd/query/main_test.go
cmd/query/utils_main_test.go
docs/slice.md
internal/core/capi.cpp
internal/core/capi.h
internal/core/core.go
internal/core/core_test.go
internal/core/cppapi.hpp
internal/core/cppapi_data.cpp
internal/core/cppapi_metadata.cpp
internal/core/ctypes.h
internal/core/regularsurface.hpp
internal/core/subvolume.cpp
internal/core/subvolume.hpp
tests/e2e/test_requests.py

API support for requesting sub-slices / cropped slices

---

README.md

Describe how to setup the python environment for the e2e tests.

Add requirements step to Readme e2e guide

---

api/endpoint.go
cmd/query/main_test.go
cmd/query/utils_main_test.go

Add proper error message for invalid API requests

---

tests/e2e/test_requests.py

One of the e2e test cases is failing in our master code due to my previous pull request. This fix will address that issue.

Adjust values precision in e2e testcases

---

docs/index.html

Do we want to add a tab icon?
Close #226

Rename title page

---

.github/actions/load_openvds_image/action.yaml
.github/workflows/analyzer.yaml
.github/workflows/e2e.yaml
.github/workflows/performance.yaml
.github/workflows/performance_user_input.yaml
.github/workflows/unit.yaml

Update github actions versions

---

CONTRIBUTING.md
SECURITY.md

Apply SCM policy

---

.github/workflows/snyk.yaml

Added a GitHub action to scan the Docker image every time a pull request merges into the master branch. The results will be displayed in the GitHub action logs.
closes #224

Add snyk to test docker image

---

tests/e2e/test_caching.py
tests/e2e/test_security.py

Test expired sas token accessing cache

---

api/request.go
internal/core/axis.cpp
internal/core/axis.hpp
internal/core/core_attributes_test.go
internal/core/cppapi_data.cpp
internal/core/subvolume.cpp
internal/core/subvolume.hpp
tests/gtest/cppapi_test.cpp
tests/gtest/subvolume_test.cpp

Interpolation near border

---

internal/core/axis.cpp
internal/core/axis.hpp

Remove unused code
Minor style changes

Clean up axis class

---

internal/core/capi.cpp
internal/core/coordinate_transformer.hpp
internal/core/datahandle.cpp
internal/core/datahandle.hpp
internal/core/subvolume.hpp
testdata/cube_intersection/make_intersecting_cubes.py
tests/gtest/coordinate_transformer_test.cpp
tests/gtest/cppapi_test.cpp
tests/gtest/datahandle_attribute_test.cpp
tests/gtest/datahandle_fence_test.cpp
tests/gtest/datahandle_metadata_test.cpp
tests/gtest/datahandle_slice_test.cpp
tests/gtest/datahandle_test.cpp

Cleans up calls a bit with intention of reusing functionality where makes sense.
Adds few testcases which reveal some bugs.

Dependency cleanup

---

internal/core/core_attributes_test.go
internal/core/subvolume.cpp
internal/core/subvolume.hpp
tests/gtest/test_utils.cpp

Resolves the issue raised by PO

Assure enough samples for calculation
